version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb_container
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inner_network
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress_container
    depends_on:
      - mariadb
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inner_network
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx_container
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inner_network
    restart: always

volumes:
  db_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hyeondle/data/db

  wordpress_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hyeondle/data/wordpress

networks:
  inner_network:
    driver: bridge
